/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Simulation Schema */
        get: operations["get_simulation_schema_api_v1_schema_simulation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Presets */
        get: operations["get_presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Progress */
        get: operations["get_run_progress_api_v1_runs__run_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Run Metadata */
        patch: operations["update_run_metadata_api_v1_runs__run_id__metadata_patch"];
        trace?: never;
    };
    "/api/v1/runs/{run_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Log */
        get: operations["get_run_log_api_v1_runs__run_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/observables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Observables */
        get: operations["list_observables_api_v1_runs__run_id__observables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/observables/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Observable */
        get: operations["get_observable_api_v1_runs__run_id__observables__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/green-functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Green Functions */
        get: operations["list_green_functions_api_v1_runs__run_id__green_functions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/green-functions/{component}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Green Function Slice */
        get: operations["get_green_function_slice_api_v1_runs__run_id__green_functions__component__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/thermal-branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Thermal Branch */
        get: operations["list_thermal_branch_api_v1_runs__run_id__thermal_branch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/thermal-branch/{component}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thermal Branch Slice */
        get: operations["get_thermal_branch_slice_api_v1_runs__run_id__thermal_branch__component__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/mixed-green-functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mixed Green Functions */
        get: operations["list_mixed_green_functions_api_v1_runs__run_id__mixed_green_functions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/mixed-green-functions/{component}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mixed Green Function Slice */
        get: operations["get_mixed_green_function_slice_api_v1_runs__run_id__mixed_green_functions__component__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Studies */
        get: operations["list_studies_api_v1_studies_get"];
        put?: never;
        /** Create Study */
        post: operations["create_study_api_v1_studies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Study */
        get: operations["get_study_api_v1_studies__study_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Groups */
        get: operations["list_job_groups_api_v1_job_groups_get"];
        put?: never;
        /** Create Job Group */
        post: operations["create_job_group_api_v1_job_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-groups/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Job Group */
        post: operations["launch_job_group_api_v1_job_groups_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Group */
        get: operations["get_job_group_api_v1_job_groups__group_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sweeps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sweeps */
        get: operations["list_sweeps_api_v1_sweeps_get"];
        put?: never;
        /** Create Sweep */
        post: operations["create_sweep_api_v1_sweeps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sweeps/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Sweep */
        post: operations["launch_sweep_api_v1_sweeps_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sweeps/{sweep_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sweep */
        get: operations["get_sweep_api_v1_sweeps__sweep_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decision Notes */
        get: operations["list_decision_notes_api_v1_decision_notes_get"];
        put?: never;
        /** Create Decision Note */
        post: operations["create_decision_note_api_v1_decision_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decision Note */
        get: operations["get_decision_note_api_v1_decision_notes__note_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/derived-analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Derived Analyses */
        get: operations["list_derived_analyses_api_v1_derived_analyses_get"];
        put?: never;
        /** Create Derived Analysis */
        post: operations["create_derived_analysis_api_v1_derived_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/derived-analyses/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch Derived Analysis */
        post: operations["launch_derived_analysis_api_v1_derived_analyses_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/derived-analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Derived Analysis */
        get: operations["get_derived_analysis_api_v1_derived_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/derived-analyses/{analysis_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Derived Analysis Result */
        get: operations["get_derived_analysis_result_api_v1_derived_analyses__analysis_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence-bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Bundles */
        get: operations["list_evidence_bundles_api_v1_evidence_bundles_get"];
        put?: never;
        /** Create Evidence Bundle */
        post: operations["create_evidence_bundle_api_v1_evidence_bundles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence-bundles/{bundle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Bundle */
        get: operations["get_evidence_bundle_api_v1_evidence_bundles__bundle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Evidence Bundle */
        patch: operations["update_evidence_bundle_api_v1_evidence_bundles__bundle_id__patch"];
        trace?: never;
    };
    "/api/v1/evidence-bundles/{bundle_id}/resolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Bundle Resolved */
        get: operations["get_evidence_bundle_resolved_api_v1_evidence_bundles__bundle_id__resolved_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdaptiveConfig */
        AdaptiveConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Atol
             * @default 1e-7
             */
            atol: number;
            /**
             * Rtol
             * @default 0.00001
             */
            rtol: number;
            /** Min Dt */
            min_dt?: number | null;
            /** Max Dt */
            max_dt?: number | null;
            /**
             * Max Growth
             * @default 2
             */
            max_growth: number;
            /**
             * Min Shrink
             * @default 0.25
             */
            min_shrink: number;
        };
        /**
         * ArtifactLifecycleState
         * @enum {string}
         */
        ArtifactLifecycleState: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** ArtifactRef */
        ArtifactRef: {
            artifact_kind: components["schemas"]["ArtifactSourceKind"];
            /** Artifact Id */
            artifact_id: string;
        };
        /**
         * ArtifactSourceKind
         * @enum {string}
         */
        ArtifactSourceKind: "run" | "job_group" | "sweep" | "analysis";
        /**
         * BoundaryCondition
         * @enum {string}
         */
        BoundaryCondition: "periodic" | "open";
        /**
         * ComparisonKind
         * @enum {string}
         */
        ComparisonKind: "physics_hypothesis" | "numerical_validation" | "regression";
        /** DecisionNoteCreate */
        DecisionNoteCreate: {
            /** Study Id */
            study_id: string;
            source_kind: components["schemas"]["ArtifactSourceKind"];
            /** Source Id */
            source_id: string;
            note_kind: components["schemas"]["DecisionNoteKind"];
            /** Body */
            body: string;
            /** Tags */
            tags?: string[];
        };
        /**
         * DecisionNoteKind
         * @enum {string}
         */
        DecisionNoteKind: "observation" | "failure" | "decision" | "todo";
        /** DecisionNoteRecord */
        DecisionNoteRecord: {
            /** Study Id */
            study_id: string;
            source_kind: components["schemas"]["ArtifactSourceKind"];
            /** Source Id */
            source_id: string;
            note_kind: components["schemas"]["DecisionNoteKind"];
            /** Body */
            body: string;
            /** Tags */
            tags?: string[];
            /** Note Id */
            note_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DerivedAnalysisArtifactCreate */
        DerivedAnalysisArtifactCreate: {
            /** Study Id */
            study_id: string;
            source_kind: components["schemas"]["DerivedAnalysisSourceKind"];
            /** Source Id */
            source_id: string;
            /** Analysis Type */
            analysis_type: string;
            /**
             * Analysis Version
             * @default v1
             */
            analysis_version: string;
            /** Cache Key */
            cache_key: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** @default queued */
            status: components["schemas"]["ArtifactLifecycleState"];
            /** Input Surface Ids */
            input_surface_ids?: string[];
            /** Result Metadata */
            result_metadata?: {
                [key: string]: unknown;
            };
            /** Data Refs */
            data_refs?: string[];
            /** Supports Bundle Ids */
            supports_bundle_ids?: string[];
        };
        /** DerivedAnalysisArtifactRecord */
        DerivedAnalysisArtifactRecord: {
            /** Study Id */
            study_id: string;
            source_kind: components["schemas"]["DerivedAnalysisSourceKind"];
            /** Source Id */
            source_id: string;
            /** Analysis Type */
            analysis_type: string;
            /**
             * Analysis Version
             * @default v1
             */
            analysis_version: string;
            /** Cache Key */
            cache_key: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** @default queued */
            status: components["schemas"]["ArtifactLifecycleState"];
            /** Input Surface Ids */
            input_surface_ids?: string[];
            /** Result Metadata */
            result_metadata?: {
                [key: string]: unknown;
            };
            /** Data Refs */
            data_refs?: string[];
            /** Supports Bundle Ids */
            supports_bundle_ids?: string[];
            /** Analysis Id */
            analysis_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DerivedAnalysisLaunchRequest */
        DerivedAnalysisLaunchRequest: {
            /** Study Id */
            study_id: string;
            source_kind: components["schemas"]["DerivedAnalysisSourceKind"];
            /** Source Id */
            source_id: string;
            /** Analysis Type */
            analysis_type: string;
            /**
             * Analysis Version
             * @default v1
             */
            analysis_version: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Input Surface Ids */
            input_surface_ids?: string[];
        };
        /** DerivedAnalysisResultRecord */
        DerivedAnalysisResultRecord: {
            analysis: components["schemas"]["DerivedAnalysisArtifactRecord"];
            /** Payload Kind */
            payload_kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * DerivedAnalysisSourceKind
         * @enum {string}
         */
        DerivedAnalysisSourceKind: "run" | "job_group" | "sweep";
        /** DriveConfig */
        DriveConfig: {
            /** @default gaussian */
            drive_type: components["schemas"]["DriveKind"];
            /**
             * Amplitude X
             * @default 0
             */
            amplitude_x: number;
            /**
             * Amplitude Y
             * @default 0
             */
            amplitude_y: number;
            /**
             * Frequency
             * @default 0
             */
            frequency: number;
            /**
             * Phase
             * @default 0
             */
            phase: number;
            /**
             * Center
             * @default 0
             */
            center: number;
            /**
             * Width
             * @default 1
             */
            width: number;
        };
        /**
         * DriveKind
         * @enum {string}
         */
        DriveKind: "gaussian" | "sine" | "sech2" | "trapezoid";
        /** EquilibriumConfig */
        EquilibriumConfig: {
            /** @default auto */
            method: components["schemas"]["EquilibriumMethod"];
            /**
             * Allow Approximation Mismatch
             * @default false
             */
            allow_approximation_mismatch: boolean;
        };
        /**
         * EquilibriumMethod
         * @enum {string}
         */
        EquilibriumMethod: "auto" | "hfb" | "second_born_reference";
        /** EvidenceBundleCreate */
        EvidenceBundleCreate: {
            /** Study Id */
            study_id: string;
            /** Title */
            title: string;
            /** Claim Candidate */
            claim_candidate: string;
            /** Artifact Refs */
            artifact_refs?: components["schemas"]["ArtifactRef"][];
            /** Analysis Refs */
            analysis_refs?: string[];
            /** Validation Scope */
            validation_scope?: string | null;
            /** Reproduction Recipe */
            reproduction_recipe?: string | null;
            /** @default draft */
            status: components["schemas"]["EvidenceBundleStatus"];
        };
        /** EvidenceBundlePatch */
        EvidenceBundlePatch: {
            /** Title */
            title?: string | null;
            /** Claim Candidate */
            claim_candidate?: string | null;
            /** Artifact Refs */
            artifact_refs?: components["schemas"]["ArtifactRef"][] | null;
            /** Analysis Refs */
            analysis_refs?: string[] | null;
            /** Validation Scope */
            validation_scope?: string | null;
            /** Reproduction Recipe */
            reproduction_recipe?: string | null;
            status?: components["schemas"]["EvidenceBundleStatus"] | null;
        };
        /** EvidenceBundleRecord */
        EvidenceBundleRecord: {
            /** Study Id */
            study_id: string;
            /** Title */
            title: string;
            /** Claim Candidate */
            claim_candidate: string;
            /** Artifact Refs */
            artifact_refs?: components["schemas"]["ArtifactRef"][];
            /** Analysis Refs */
            analysis_refs?: string[];
            /** Validation Scope */
            validation_scope?: string | null;
            /** Reproduction Recipe */
            reproduction_recipe?: string | null;
            /** @default draft */
            status: components["schemas"]["EvidenceBundleStatus"];
            /** Bundle Id */
            bundle_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EvidenceBundleResolvedAnalysis */
        EvidenceBundleResolvedAnalysis: {
            /** Analysis Id */
            analysis_id: string;
            /** Study Id */
            study_id: string;
            /** Analysis Type */
            analysis_type: string;
            /** Analysis Version */
            analysis_version: string;
            source_kind: components["schemas"]["DerivedAnalysisSourceKind"];
            /** Source Id */
            source_id: string;
            status: components["schemas"]["ArtifactLifecycleState"];
            /** Result Metadata */
            result_metadata?: {
                [key: string]: unknown;
            };
            /** Supports Bundle Ids */
            supports_bundle_ids?: string[];
        };
        /** EvidenceBundleResolvedArtifact */
        EvidenceBundleResolvedArtifact: {
            artifact_kind: components["schemas"]["ArtifactSourceKind"];
            /** Artifact Id */
            artifact_id: string;
            /** Study Id */
            study_id?: string | null;
            /** Label */
            label: string;
            /** State */
            state?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** EvidenceBundleResolvedRecord */
        EvidenceBundleResolvedRecord: {
            bundle: components["schemas"]["EvidenceBundleRecord"];
            /** Resolved Artifacts */
            resolved_artifacts?: components["schemas"]["EvidenceBundleResolvedArtifact"][];
            /** Resolved Analyses */
            resolved_analyses?: components["schemas"]["EvidenceBundleResolvedAnalysis"][];
        };
        /**
         * EvidenceBundleStatus
         * @enum {string}
         */
        EvidenceBundleStatus: "draft" | "ready" | "superseded";
        /** GreenFunctionCatalogResponse */
        GreenFunctionCatalogResponse: {
            /** Run Id */
            run_id: string;
            /** Components */
            components: string[];
            /** Shape */
            shape: number[];
            /** Time Point Count */
            time_point_count: number;
            /** Nambu Dimension */
            nambu_dimension: number;
        };
        /** GreenFunctionSliceResponse */
        GreenFunctionSliceResponse: {
            /** Component */
            component: string;
            /** Times Row */
            times_row: number[];
            /** Times Col */
            times_col: number[];
            /** Nambu Start */
            nambu_start: number;
            /** Nambu Stop */
            nambu_stop: number;
            /** Shape */
            shape: number[];
            /** Real */
            real: number[][][][];
            /** Imag */
            imag: number[][][][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitialStateConfig */
        InitialStateConfig: {
            /**
             * Filling
             * @default 0.5
             */
            filling: number;
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
            /**
             * Seed Pairing
             * @default 0
             */
            seed_pairing: number;
        };
        /** InteractionConfig */
        InteractionConfig: {
            /**
             * Onsite U
             * @default 0
             */
            onsite_u: number;
            /**
             * Nearest Neighbor V
             * @default 0
             */
            nearest_neighbor_v: number;
            /** @default none */
            pairing_channel: components["schemas"]["PairingChannel"];
        };
        /** JobGroupCreate */
        JobGroupCreate: {
            /** Study Id */
            study_id: string;
            /** Name */
            name: string;
            comparison_kind: components["schemas"]["ComparisonKind"];
            /** Baseline Run Id */
            baseline_run_id?: string | null;
            /** Base Config */
            base_config?: {
                [key: string]: unknown;
            };
            /** Variants */
            variants?: components["schemas"]["JobGroupVariant"][];
            /** Child Run Ids */
            child_run_ids?: string[];
        };
        /** JobGroupLaunchRequest */
        JobGroupLaunchRequest: {
            /** Study Id */
            study_id: string;
            /** Name */
            name: string;
            comparison_kind: components["schemas"]["ComparisonKind"];
            /** Baseline Run Id */
            baseline_run_id?: string | null;
            /** Base Config */
            base_config?: {
                [key: string]: unknown;
            };
            /** Variants */
            variants?: components["schemas"]["JobGroupVariant"][];
        };
        /** JobGroupRecord */
        JobGroupRecord: {
            /** Study Id */
            study_id: string;
            /** Name */
            name: string;
            comparison_kind: components["schemas"]["ComparisonKind"];
            /** Baseline Run Id */
            baseline_run_id?: string | null;
            /** Base Config */
            base_config?: {
                [key: string]: unknown;
            };
            /** Variants */
            variants?: components["schemas"]["JobGroupVariant"][];
            /** Child Run Ids */
            child_run_ids?: string[];
            /** Group Id */
            group_id: string;
            state: components["schemas"]["ArtifactLifecycleState"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobGroupVariant */
        JobGroupVariant: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** Config Patch */
            config_patch?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id?: string | null;
        };
        /** KBEConfig */
        KBEConfig: {
            /** @default hfb */
            self_energy: components["schemas"]["KBESelfEnergyMode"];
            /**
             * Max Fixed Point Iterations
             * @default 6
             */
            max_fixed_point_iterations: number;
            /**
             * Tolerance
             * @default 1e-7
             */
            tolerance: number;
            /**
             * Mixing
             * @default 0.35
             */
            mixing: number;
            /** Memory Window */
            memory_window?: number | null;
        };
        /**
         * KBESelfEnergyMode
         * @enum {string}
         */
        KBESelfEnergyMode: "hfb" | "second_born" | "second_born_reference";
        /** LatticeConfig */
        LatticeConfig: {
            /**
             * Kind
             * @default square
             */
            kind: string;
            /** Nx */
            nx: number;
            /** Ny */
            ny: number;
            /** @default periodic */
            boundary: components["schemas"]["BoundaryCondition"];
            /**
             * Hopping
             * @default 1
             */
            hopping: number;
            /**
             * Chemical Potential
             * @default 0
             */
            chemical_potential: number;
        };
        /** MixedGreenFunctionCatalogResponse */
        MixedGreenFunctionCatalogResponse: {
            /** Run Id */
            run_id: string;
            /** Components */
            components: string[];
            /** Shape */
            shape: number[];
            /** Time Point Count */
            time_point_count: number;
            /** Tau Point Count */
            tau_point_count: number;
            /** Nambu Dimension */
            nambu_dimension: number;
        };
        /** MixedGreenFunctionSliceResponse */
        MixedGreenFunctionSliceResponse: {
            /** Component */
            component: string;
            /** Times */
            times: number[];
            /** Tau */
            tau: number[];
            /** Nambu Start */
            nambu_start: number;
            /** Nambu Stop */
            nambu_stop: number;
            /** Shape */
            shape: number[];
            /** Real */
            real: number[][][][];
            /** Imag */
            imag: number[][][][];
        };
        /** ObservableCatalogResponse */
        ObservableCatalogResponse: {
            /** Run Id */
            run_id: string;
            /** Observables */
            observables: string[];
        };
        /** ObservableDescriptor */
        ObservableDescriptor: {
            /** Name */
            name: string;
            /** Time Key */
            time_key: string;
            /** Series */
            series: components["schemas"]["ObservableSeriesDescriptor"][];
            /** Units */
            units?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ObservableResponse */
        ObservableResponse: {
            /** Name */
            name: string;
            /** Time */
            time: number[];
            /** Series */
            series: components["schemas"]["ObservableSeries"][];
            /** Units */
            units?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ObservableSeries */
        ObservableSeries: {
            /** Label */
            label: string;
            /** Values */
            values: number[];
        };
        /** ObservableSeriesDescriptor */
        ObservableSeriesDescriptor: {
            /** Label */
            label: string;
            /** Key */
            key: string;
        };
        /**
         * PairingChannel
         * @enum {string}
         */
        PairingChannel: "none" | "onsite" | "bond_s" | "bond_d";
        /**
         * ParameterKind
         * @enum {string}
         */
        ParameterKind: "physics" | "numerical" | "analysis";
        /**
         * PresetCategory
         * @enum {string}
         */
        PresetCategory: "demo" | "working_baseline" | "mean_field" | "exact_baseline";
        /**
         * PresetEntry
         * @description Enriched preset: config + metadata for display and selection.
         */
        PresetEntry: {
            /** Name */
            name: string;
            category: components["schemas"]["PresetCategory"];
            validation_status: components["schemas"]["PresetValidationStatus"];
            /** Summary */
            summary: string;
            /** Scope Note */
            scope_note: string;
            /** Primary Observable */
            primary_observable?: string | null;
            config: components["schemas"]["SimulationConfig-Output"];
        };
        /**
         * PresetValidationStatus
         * @enum {string}
         */
        PresetValidationStatus: "validated" | "partial" | "prototype";
        /**
         * ResearchValidationStatus
         * @enum {string}
         */
        ResearchValidationStatus: "unchecked" | "screening" | "accepted" | "rejected";
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Name */
            name?: string | null;
            /** Solver */
            solver: string;
            state: components["schemas"]["RunState"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Status Message */
            status_message?: string | null;
            /** Lattice */
            lattice: {
                [key: string]: unknown;
            };
            /** Time Grid */
            time_grid: {
                [key: string]: unknown;
            };
            /** Available Observables */
            available_observables?: components["schemas"]["ObservableDescriptor"][];
            /** Diagnostics Excerpt */
            diagnostics_excerpt?: {
                [key: string]: unknown;
            };
            research_metadata?: components["schemas"]["RunResearchMetadata"];
            config: components["schemas"]["SimulationConfig-Output"];
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            };
        };
        /**
         * RunProgressPhase
         * @enum {string}
         */
        RunProgressPhase: "queued" | "equilibrium" | "propagating" | "thermal_branch" | "mixed_branch" | "finalizing" | "succeeded" | "failed" | "cancelled";
        /** RunProgressPoint */
        RunProgressPoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Wall Seconds Elapsed */
            wall_seconds_elapsed: number;
            /** Physical Time Current */
            physical_time_current?: number | null;
            /** Physical Progress Fraction */
            physical_progress_fraction?: number | null;
            /**
             * Saved Samples Written
             * @default 0
             */
            saved_samples_written: number;
            /** Metric 1 */
            metric_1?: number | null;
            /** Metric 2 */
            metric_2?: number | null;
            /** Metric 3 */
            metric_3?: number | null;
        };
        /** RunProgressRecord */
        RunProgressRecord: {
            /** Run Id */
            run_id: string;
            state: components["schemas"]["RunState"];
            phase: components["schemas"]["RunProgressPhase"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Wall Seconds Elapsed
             * @default 0
             */
            wall_seconds_elapsed: number;
            /** Physical Time Current */
            physical_time_current?: number | null;
            /** Physical Time Final */
            physical_time_final?: number | null;
            /** Physical Progress Fraction */
            physical_progress_fraction?: number | null;
            /**
             * Accepted Steps
             * @default 0
             */
            accepted_steps: number;
            /**
             * Requested Steps
             * @default 0
             */
            requested_steps: number;
            /**
             * Rejected Steps
             * @default 0
             */
            rejected_steps: number;
            /**
             * Saved Samples Written
             * @default 0
             */
            saved_samples_written: number;
            /** Status Line */
            status_line?: string | null;
            /** Solver Metrics */
            solver_metrics?: {
                [key: string]: unknown;
            };
            /** History */
            history?: components["schemas"]["RunProgressPoint"][];
        };
        /** RunResearchMetadata */
        RunResearchMetadata: {
            /** Study Id */
            study_id?: string | null;
            run_role?: components["schemas"]["RunRole"] | null;
            /** @default unchecked */
            validation_status: components["schemas"]["ResearchValidationStatus"];
            /** Failure Tags */
            failure_tags?: string[];
            /** Group Id */
            group_id?: string | null;
            /** Sweep Id */
            sweep_id?: string | null;
            /** Variant Label */
            variant_label?: string | null;
            /** Preset Id */
            preset_id?: string | null;
            /** Tags */
            tags?: string[];
            /** Config Hash */
            config_hash?: string | null;
            /** Code Version */
            code_version?: string | null;
            /** Storage Uri */
            storage_uri?: string | null;
        };
        /** RunResearchMetadataPatch */
        RunResearchMetadataPatch: {
            /** Study Id */
            study_id?: string | null;
            run_role?: components["schemas"]["RunRole"] | null;
            validation_status?: components["schemas"]["ResearchValidationStatus"] | null;
            /** Failure Tags */
            failure_tags?: string[] | null;
            /** Group Id */
            group_id?: string | null;
            /** Sweep Id */
            sweep_id?: string | null;
            /** Variant Label */
            variant_label?: string | null;
            /** Preset Id */
            preset_id?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Code Version */
            code_version?: string | null;
        };
        /**
         * RunRole
         * @enum {string}
         */
        RunRole: "baseline" | "candidate" | "control" | "numerical_check";
        /**
         * RunState
         * @enum {string}
         */
        RunState: "queued" | "running" | "succeeded" | "succeeded_with_warnings" | "failed" | "cancelled";
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Name */
            name?: string | null;
            /** Solver */
            solver: string;
            state: components["schemas"]["RunState"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Status Message */
            status_message?: string | null;
            /** Lattice */
            lattice: {
                [key: string]: unknown;
            };
            /** Time Grid */
            time_grid: {
                [key: string]: unknown;
            };
            /** Available Observables */
            available_observables?: components["schemas"]["ObservableDescriptor"][];
            /** Diagnostics Excerpt */
            diagnostics_excerpt?: {
                [key: string]: unknown;
            };
            research_metadata?: components["schemas"]["RunResearchMetadata"];
        };
        /** SimulationConfig */
        "SimulationConfig-Input": {
            /** Name */
            name?: string | null;
            /** @default noninteracting */
            solver: components["schemas"]["SolverKind"];
            /** @default real_space */
            representation: components["schemas"]["SolverRepresentation"];
            lattice: components["schemas"]["LatticeConfig"];
            time: components["schemas"]["TimeGridConfig"];
            drive?: components["schemas"]["DriveConfig"];
            interaction?: components["schemas"]["InteractionConfig"];
            initial_state?: components["schemas"]["InitialStateConfig"];
            equilibrium?: components["schemas"]["EquilibriumConfig"];
            kbe?: components["schemas"]["KBEConfig"];
            adaptive?: components["schemas"]["AdaptiveConfig"];
            thermal_branch?: components["schemas"]["ThermalBranchConfig"];
            /** Observables */
            observables?: string[];
        };
        /** SimulationConfig */
        "SimulationConfig-Output": {
            /** Name */
            name?: string | null;
            /** @default noninteracting */
            solver: components["schemas"]["SolverKind"];
            /** @default real_space */
            representation: components["schemas"]["SolverRepresentation"];
            lattice: components["schemas"]["LatticeConfig"];
            time: components["schemas"]["TimeGridConfig"];
            drive?: components["schemas"]["DriveConfig"];
            interaction?: components["schemas"]["InteractionConfig"];
            initial_state?: components["schemas"]["InitialStateConfig"];
            equilibrium?: components["schemas"]["EquilibriumConfig"];
            kbe?: components["schemas"]["KBEConfig"];
            adaptive?: components["schemas"]["AdaptiveConfig"];
            thermal_branch?: components["schemas"]["ThermalBranchConfig"];
            /** Observables */
            observables?: string[];
        };
        /**
         * SolverKind
         * @enum {string}
         */
        SolverKind: "noninteracting" | "tdhfb" | "kbe_hfb";
        /**
         * SolverRepresentation
         * @enum {string}
         */
        SolverRepresentation: "real_space" | "k_space";
        /** StudyCreate */
        StudyCreate: {
            /** Title */
            title: string;
            /** Question */
            question: string;
            /** Baseline Preset Id */
            baseline_preset_id?: string | null;
            /** Target Observables */
            target_observables?: string[];
            /** Primary Surfaces */
            primary_surfaces?: string[];
            /** Acceptance Checks */
            acceptance_checks?: string[];
            /** @default planning */
            status: components["schemas"]["StudyStatus"];
            /** Notes On Scope */
            notes_on_scope?: string | null;
        };
        /** StudyRecord */
        StudyRecord: {
            /** Title */
            title: string;
            /** Question */
            question: string;
            /** Baseline Preset Id */
            baseline_preset_id?: string | null;
            /** Target Observables */
            target_observables?: string[];
            /** Primary Surfaces */
            primary_surfaces?: string[];
            /** Acceptance Checks */
            acceptance_checks?: string[];
            /** @default planning */
            status: components["schemas"]["StudyStatus"];
            /** Notes On Scope */
            notes_on_scope?: string | null;
            /** Study Id */
            study_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * StudyStatus
         * @enum {string}
         */
        StudyStatus: "planning" | "active" | "paused" | "completed" | "archived";
        /** SweepCreate */
        SweepCreate: {
            /** Study Id */
            study_id: string;
            /** Name */
            name: string;
            parameter_kind: components["schemas"]["ParameterKind"];
            /** Parameter Path */
            parameter_path: string;
            /** Parameter Label */
            parameter_label: string;
            /** Values */
            values?: (string | number | boolean)[];
            /** Baseline Value */
            baseline_value?: string | number | boolean | null;
            /** Fixed Axes */
            fixed_axes?: {
                [key: string]: unknown;
            };
            /** Child Run Ids */
            child_run_ids?: string[];
        };
        /** SweepLaunchRequest */
        SweepLaunchRequest: {
            /** Study Id */
            study_id: string;
            /** Name */
            name: string;
            parameter_kind: components["schemas"]["ParameterKind"];
            /** Parameter Path */
            parameter_path: string;
            /** Parameter Label */
            parameter_label: string;
            /** Values */
            values?: (string | number | boolean)[];
            /** Baseline Value */
            baseline_value?: string | number | boolean | null;
            /** Fixed Axes */
            fixed_axes?: {
                [key: string]: unknown;
            };
            /** Base Config */
            base_config?: {
                [key: string]: unknown;
            };
        };
        /** SweepRecord */
        SweepRecord: {
            /** Study Id */
            study_id: string;
            /** Name */
            name: string;
            parameter_kind: components["schemas"]["ParameterKind"];
            /** Parameter Path */
            parameter_path: string;
            /** Parameter Label */
            parameter_label: string;
            /** Values */
            values?: (string | number | boolean)[];
            /** Baseline Value */
            baseline_value?: string | number | boolean | null;
            /** Fixed Axes */
            fixed_axes?: {
                [key: string]: unknown;
            };
            /** Child Run Ids */
            child_run_ids?: string[];
            /** Sweep Id */
            sweep_id: string;
            state: components["schemas"]["ArtifactLifecycleState"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ThermalBranchCatalogResponse */
        ThermalBranchCatalogResponse: {
            /** Run Id */
            run_id: string;
            /** Components */
            components: string[];
            /** Shape */
            shape: number[];
            /** Tau Point Count */
            tau_point_count: number;
            /** Nambu Dimension */
            nambu_dimension: number;
        };
        /** ThermalBranchConfig */
        ThermalBranchConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * N Tau
             * @default 16
             */
            n_tau: number;
            /**
             * Max Iterations
             * @default 8
             */
            max_iterations: number;
            /**
             * Mixing
             * @default 0.3
             */
            mixing: number;
        };
        /** ThermalBranchSliceResponse */
        ThermalBranchSliceResponse: {
            /** Component */
            component: string;
            /** Tau */
            tau: number[];
            /** Nambu Start */
            nambu_start: number;
            /** Nambu Stop */
            nambu_stop: number;
            /** Shape */
            shape: number[];
            /** Real */
            real: number[][][];
            /** Imag */
            imag: number[][][];
        };
        /** TimeGridConfig */
        TimeGridConfig: {
            /** T Final */
            t_final: number;
            /** Dt */
            dt: number;
            /**
             * Save Every
             * @default 1
             */
            save_every: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_simulation_schema_api_v1_schema_simulation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetEntry"][];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationConfig-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_progress_api_v1_runs__run_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunProgressRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_run_metadata_api_v1_runs__run_id__metadata_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunResearchMetadataPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_log_api_v1_runs__run_id__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_observables_api_v1_runs__run_id__observables_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservableCatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observable_api_v1_runs__run_id__observables__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_green_functions_api_v1_runs__run_id__green_functions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreenFunctionCatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_green_function_slice_api_v1_runs__run_id__green_functions__component__get: {
        parameters: {
            query?: {
                row_start?: number | null;
                row_stop?: number | null;
                col_start?: number | null;
                col_stop?: number | null;
                nambu_start?: number | null;
                nambu_stop?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
                component: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreenFunctionSliceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_thermal_branch_api_v1_runs__run_id__thermal_branch_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThermalBranchCatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thermal_branch_slice_api_v1_runs__run_id__thermal_branch__component__get: {
        parameters: {
            query?: {
                tau_start?: number | null;
                tau_stop?: number | null;
                nambu_start?: number | null;
                nambu_stop?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
                component: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThermalBranchSliceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mixed_green_functions_api_v1_runs__run_id__mixed_green_functions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixedGreenFunctionCatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mixed_green_function_slice_api_v1_runs__run_id__mixed_green_functions__component__get: {
        parameters: {
            query?: {
                time_start?: number | null;
                time_stop?: number | null;
                tau_start?: number | null;
                tau_stop?: number | null;
                nambu_start?: number | null;
                nambu_stop?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
                component: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixedGreenFunctionSliceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_studies_api_v1_studies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyRecord"][];
                };
            };
        };
    };
    create_study_api_v1_studies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_study_api_v1_studies__study_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_groups_api_v1_job_groups_get: {
        parameters: {
            query?: {
                study_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobGroupRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_group_api_v1_job_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobGroupRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_job_group_api_v1_job_groups_launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobGroupLaunchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobGroupRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_group_api_v1_job_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobGroupRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sweeps_api_v1_sweeps_get: {
        parameters: {
            query?: {
                study_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sweep_api_v1_sweeps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_sweep_api_v1_sweeps_launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepLaunchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sweep_api_v1_sweeps__sweep_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sweep_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decision_notes_api_v1_decision_notes_get: {
        parameters: {
            query?: {
                study_id?: string | null;
                source_kind?: components["schemas"]["ArtifactSourceKind"] | null;
                source_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionNoteRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_decision_note_api_v1_decision_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionNoteRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decision_note_api_v1_decision_notes__note_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionNoteRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_derived_analyses_api_v1_derived_analyses_get: {
        parameters: {
            query?: {
                study_id?: string | null;
                source_kind?: components["schemas"]["DerivedAnalysisSourceKind"] | null;
                source_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivedAnalysisArtifactRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_derived_analysis_api_v1_derived_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DerivedAnalysisArtifactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivedAnalysisArtifactRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_derived_analysis_api_v1_derived_analyses_launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DerivedAnalysisLaunchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivedAnalysisArtifactRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_derived_analysis_api_v1_derived_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivedAnalysisArtifactRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_derived_analysis_result_api_v1_derived_analyses__analysis_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivedAnalysisResultRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_bundles_api_v1_evidence_bundles_get: {
        parameters: {
            query?: {
                study_id?: string | null;
                status?: components["schemas"]["EvidenceBundleStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceBundleRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evidence_bundle_api_v1_evidence_bundles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceBundleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceBundleRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_bundle_api_v1_evidence_bundles__bundle_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceBundleRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_evidence_bundle_api_v1_evidence_bundles__bundle_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceBundlePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceBundleRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_bundle_resolved_api_v1_evidence_bundles__bundle_id__resolved_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceBundleResolvedRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
