/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/health": {
    /** Health */
    get: operations["health_api_v1_health_get"];
  };
  "/api/v1/schema/simulation": {
    /** Get Simulation Schema */
    get: operations["get_simulation_schema_api_v1_schema_simulation_get"];
  };
  "/api/v1/presets": {
    /** Get Presets */
    get: operations["get_presets_api_v1_presets_get"];
  };
  "/api/v1/runs": {
    /** List Runs */
    get: operations["list_runs_api_v1_runs_get"];
    /** Create Run */
    post: operations["create_run_api_v1_runs_post"];
  };
  "/api/v1/runs/{run_id}": {
    /** Get Run */
    get: operations["get_run_api_v1_runs__run_id__get"];
  };
  "/api/v1/runs/{run_id}/cancel": {
    /** Cancel Run */
    post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
  };
  "/api/v1/runs/{run_id}/observables": {
    /** List Observables */
    get: operations["list_observables_api_v1_runs__run_id__observables_get"];
  };
  "/api/v1/runs/{run_id}/observables/{name}": {
    /** Get Observable */
    get: operations["get_observable_api_v1_runs__run_id__observables__name__get"];
  };
  "/api/v1/runs/{run_id}/green-functions": {
    /** List Green Functions */
    get: operations["list_green_functions_api_v1_runs__run_id__green_functions_get"];
  };
  "/api/v1/runs/{run_id}/green-functions/{component}": {
    /** Get Green Function Slice */
    get: operations["get_green_function_slice_api_v1_runs__run_id__green_functions__component__get"];
  };
  "/api/v1/runs/{run_id}/thermal-branch": {
    /** List Thermal Branch */
    get: operations["list_thermal_branch_api_v1_runs__run_id__thermal_branch_get"];
  };
  "/api/v1/runs/{run_id}/thermal-branch/{component}": {
    /** Get Thermal Branch Slice */
    get: operations["get_thermal_branch_slice_api_v1_runs__run_id__thermal_branch__component__get"];
  };
  "/api/v1/runs/{run_id}/mixed-green-functions": {
    /** List Mixed Green Functions */
    get: operations["list_mixed_green_functions_api_v1_runs__run_id__mixed_green_functions_get"];
  };
  "/api/v1/runs/{run_id}/mixed-green-functions/{component}": {
    /** Get Mixed Green Function Slice */
    get: operations["get_mixed_green_function_slice_api_v1_runs__run_id__mixed_green_functions__component__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AdaptiveConfig */
    AdaptiveConfig: {
      /**
       * Enabled
       * @default false
       */
      enabled?: boolean;
      /**
       * Atol
       * @default 1e-7
       */
      atol?: number;
      /**
       * Rtol
       * @default 0.00001
       */
      rtol?: number;
      /** Min Dt */
      min_dt?: number | null;
      /** Max Dt */
      max_dt?: number | null;
      /**
       * Max Growth
       * @default 2
       */
      max_growth?: number;
      /**
       * Min Shrink
       * @default 0.25
       */
      min_shrink?: number;
    };
    /**
     * BoundaryCondition
     * @enum {string}
     */
    BoundaryCondition: "periodic" | "open";
    /** DriveConfig */
    DriveConfig: {
      /**
       * Amplitude X
       * @default 0
       */
      amplitude_x?: number;
      /**
       * Amplitude Y
       * @default 0
       */
      amplitude_y?: number;
      /**
       * Frequency
       * @default 0
       */
      frequency?: number;
      /**
       * Phase
       * @default 0
       */
      phase?: number;
      /**
       * Center
       * @default 0
       */
      center?: number;
      /**
       * Width
       * @default 1
       */
      width?: number;
    };
    /** GreenFunctionCatalogResponse */
    GreenFunctionCatalogResponse: {
      /** Run Id */
      run_id: string;
      /** Components */
      components: string[];
      /** Shape */
      shape: number[];
      /** Time Point Count */
      time_point_count: number;
      /** Nambu Dimension */
      nambu_dimension: number;
    };
    /** GreenFunctionSliceResponse */
    GreenFunctionSliceResponse: {
      /** Component */
      component: string;
      /** Times Row */
      times_row: number[];
      /** Times Col */
      times_col: number[];
      /** Nambu Start */
      nambu_start: number;
      /** Nambu Stop */
      nambu_stop: number;
      /** Shape */
      shape: number[];
      /** Real */
      real: number[][][][];
      /** Imag */
      imag: number[][][][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InitialStateConfig */
    InitialStateConfig: {
      /**
       * Filling
       * @default 0.5
       */
      filling?: number;
      /**
       * Temperature
       * @default 0
       */
      temperature?: number;
      /**
       * Seed Pairing
       * @default 0
       */
      seed_pairing?: number;
    };
    /** InteractionConfig */
    InteractionConfig: {
      /**
       * Onsite U
       * @default 0
       */
      onsite_u?: number;
      /**
       * Nearest Neighbor V
       * @default 0
       */
      nearest_neighbor_v?: number;
      /** @default none */
      pairing_channel?: components["schemas"]["PairingChannel"];
    };
    /** KBEConfig */
    KBEConfig: {
      /** @default hfb */
      self_energy?: components["schemas"]["KBESelfEnergyMode"];
      /**
       * Max Fixed Point Iterations
       * @default 6
       */
      max_fixed_point_iterations?: number;
      /**
       * Tolerance
       * @default 1e-7
       */
      tolerance?: number;
      /**
       * Mixing
       * @default 0.35
       */
      mixing?: number;
      /** Memory Window */
      memory_window?: number | null;
    };
    /**
     * KBESelfEnergyMode
     * @enum {string}
     */
    KBESelfEnergyMode: "hfb" | "second_born";
    /** LatticeConfig */
    LatticeConfig: {
      /**
       * Kind
       * @default square
       */
      kind?: string;
      /** Nx */
      nx: number;
      /** Ny */
      ny: number;
      /** @default periodic */
      boundary?: components["schemas"]["BoundaryCondition"];
      /**
       * Hopping
       * @default 1
       */
      hopping?: number;
      /**
       * Chemical Potential
       * @default 0
       */
      chemical_potential?: number;
    };
    /** MixedGreenFunctionCatalogResponse */
    MixedGreenFunctionCatalogResponse: {
      /** Run Id */
      run_id: string;
      /** Components */
      components: string[];
      /** Shape */
      shape: number[];
      /** Time Point Count */
      time_point_count: number;
      /** Tau Point Count */
      tau_point_count: number;
      /** Nambu Dimension */
      nambu_dimension: number;
    };
    /** MixedGreenFunctionSliceResponse */
    MixedGreenFunctionSliceResponse: {
      /** Component */
      component: string;
      /** Times */
      times: number[];
      /** Tau */
      tau: number[];
      /** Nambu Start */
      nambu_start: number;
      /** Nambu Stop */
      nambu_stop: number;
      /** Shape */
      shape: number[];
      /** Real */
      real: number[][][][];
      /** Imag */
      imag: number[][][][];
    };
    /** ObservableCatalogResponse */
    ObservableCatalogResponse: {
      /** Run Id */
      run_id: string;
      /** Observables */
      observables: string[];
    };
    /** ObservableDescriptor */
    ObservableDescriptor: {
      /** Name */
      name: string;
      /** Time Key */
      time_key: string;
      /** Series */
      series: components["schemas"]["ObservableSeriesDescriptor"][];
      /** Units */
      units?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
    };
    /** ObservableResponse */
    ObservableResponse: {
      /** Name */
      name: string;
      /** Time */
      time: number[];
      /** Series */
      series: components["schemas"]["ObservableSeries"][];
      /** Units */
      units?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
    };
    /** ObservableSeries */
    ObservableSeries: {
      /** Label */
      label: string;
      /** Values */
      values: number[];
    };
    /** ObservableSeriesDescriptor */
    ObservableSeriesDescriptor: {
      /** Label */
      label: string;
      /** Key */
      key: string;
    };
    /**
     * PairingChannel
     * @enum {string}
     */
    PairingChannel: "none" | "onsite" | "bond_s" | "bond_d";
    /** RunDetail */
    RunDetail: {
      /** Run Id */
      run_id: string;
      /** Name */
      name?: string | null;
      /** Solver */
      solver: string;
      state: components["schemas"]["RunState"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Started At */
      started_at?: string | null;
      /** Finished At */
      finished_at?: string | null;
      /** Status Message */
      status_message?: string | null;
      /** Lattice */
      lattice: {
        [key: string]: unknown;
      };
      /** Time Grid */
      time_grid: {
        [key: string]: unknown;
      };
      /** Available Observables */
      available_observables?: components["schemas"]["ObservableDescriptor"][];
      /** Diagnostics Excerpt */
      diagnostics_excerpt?: {
        [key: string]: unknown;
      };
      config: components["schemas"]["SimulationConfig-Output"];
      /** Diagnostics */
      diagnostics?: {
        [key: string]: unknown;
      };
    };
    /**
     * RunState
     * @enum {string}
     */
    RunState: "queued" | "running" | "succeeded" | "failed" | "cancelled";
    /** RunSummary */
    RunSummary: {
      /** Run Id */
      run_id: string;
      /** Name */
      name?: string | null;
      /** Solver */
      solver: string;
      state: components["schemas"]["RunState"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Started At */
      started_at?: string | null;
      /** Finished At */
      finished_at?: string | null;
      /** Status Message */
      status_message?: string | null;
      /** Lattice */
      lattice: {
        [key: string]: unknown;
      };
      /** Time Grid */
      time_grid: {
        [key: string]: unknown;
      };
      /** Available Observables */
      available_observables?: components["schemas"]["ObservableDescriptor"][];
      /** Diagnostics Excerpt */
      diagnostics_excerpt?: {
        [key: string]: unknown;
      };
    };
    /** SimulationConfig */
    "SimulationConfig-Input": {
      /** Name */
      name?: string | null;
      /** @default noninteracting */
      solver?: components["schemas"]["SolverKind"];
      lattice: components["schemas"]["LatticeConfig"];
      time: components["schemas"]["TimeGridConfig"];
      drive?: components["schemas"]["DriveConfig"];
      interaction?: components["schemas"]["InteractionConfig"];
      initial_state?: components["schemas"]["InitialStateConfig"];
      kbe?: components["schemas"]["KBEConfig"];
      adaptive?: components["schemas"]["AdaptiveConfig"];
      thermal_branch?: components["schemas"]["ThermalBranchConfig"];
      /** Observables */
      observables?: string[];
    };
    /** SimulationConfig */
    "SimulationConfig-Output": {
      /** Name */
      name?: string | null;
      /** @default noninteracting */
      solver?: components["schemas"]["SolverKind"];
      lattice: components["schemas"]["LatticeConfig"];
      time: components["schemas"]["TimeGridConfig"];
      drive?: components["schemas"]["DriveConfig"];
      interaction?: components["schemas"]["InteractionConfig"];
      initial_state?: components["schemas"]["InitialStateConfig"];
      kbe?: components["schemas"]["KBEConfig"];
      adaptive?: components["schemas"]["AdaptiveConfig"];
      thermal_branch?: components["schemas"]["ThermalBranchConfig"];
      /** Observables */
      observables?: string[];
    };
    /**
     * SolverKind
     * @enum {string}
     */
    SolverKind: "noninteracting" | "tdhfb" | "kbe_hfb";
    /** ThermalBranchCatalogResponse */
    ThermalBranchCatalogResponse: {
      /** Run Id */
      run_id: string;
      /** Components */
      components: string[];
      /** Shape */
      shape: number[];
      /** Tau Point Count */
      tau_point_count: number;
      /** Nambu Dimension */
      nambu_dimension: number;
    };
    /** ThermalBranchConfig */
    ThermalBranchConfig: {
      /**
       * Enabled
       * @default false
       */
      enabled?: boolean;
      /**
       * N Tau
       * @default 16
       */
      n_tau?: number;
      /**
       * Max Iterations
       * @default 8
       */
      max_iterations?: number;
      /**
       * Mixing
       * @default 0.3
       */
      mixing?: number;
    };
    /** ThermalBranchSliceResponse */
    ThermalBranchSliceResponse: {
      /** Component */
      component: string;
      /** Tau */
      tau: number[];
      /** Nambu Start */
      nambu_start: number;
      /** Nambu Stop */
      nambu_stop: number;
      /** Shape */
      shape: number[];
      /** Real */
      real: number[][][];
      /** Imag */
      imag: number[][][];
    };
    /** TimeGridConfig */
    TimeGridConfig: {
      /** T Final */
      t_final: number;
      /** Dt */
      dt: number;
      /**
       * Save Every
       * @default 1
       */
      save_every?: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health */
  health_api_v1_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /** Get Simulation Schema */
  get_simulation_schema_api_v1_schema_simulation_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Get Presets */
  get_presets_api_v1_presets_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SimulationConfig-Output"][];
        };
      };
    };
  };
  /** List Runs */
  list_runs_api_v1_runs_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RunSummary"][];
        };
      };
    };
  };
  /** Create Run */
  create_run_api_v1_runs_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SimulationConfig-Input"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Run */
  get_run_api_v1_runs__run_id__get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Cancel Run */
  cancel_run_api_v1_runs__run_id__cancel_post: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Observables */
  list_observables_api_v1_runs__run_id__observables_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ObservableCatalogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Observable */
  get_observable_api_v1_runs__run_id__observables__name__get: {
    parameters: {
      path: {
        run_id: string;
        name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ObservableResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Green Functions */
  list_green_functions_api_v1_runs__run_id__green_functions_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GreenFunctionCatalogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Green Function Slice */
  get_green_function_slice_api_v1_runs__run_id__green_functions__component__get: {
    parameters: {
      query?: {
        row_start?: number | null;
        row_stop?: number | null;
        col_start?: number | null;
        col_stop?: number | null;
        nambu_start?: number | null;
        nambu_stop?: number | null;
      };
      path: {
        run_id: string;
        component: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GreenFunctionSliceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Thermal Branch */
  list_thermal_branch_api_v1_runs__run_id__thermal_branch_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThermalBranchCatalogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Thermal Branch Slice */
  get_thermal_branch_slice_api_v1_runs__run_id__thermal_branch__component__get: {
    parameters: {
      query?: {
        tau_start?: number | null;
        tau_stop?: number | null;
        nambu_start?: number | null;
        nambu_stop?: number | null;
      };
      path: {
        run_id: string;
        component: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThermalBranchSliceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Mixed Green Functions */
  list_mixed_green_functions_api_v1_runs__run_id__mixed_green_functions_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MixedGreenFunctionCatalogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Mixed Green Function Slice */
  get_mixed_green_function_slice_api_v1_runs__run_id__mixed_green_functions__component__get: {
    parameters: {
      query?: {
        time_start?: number | null;
        time_stop?: number | null;
        tau_start?: number | null;
        tau_stop?: number | null;
        nambu_start?: number | null;
        nambu_stop?: number | null;
      };
      path: {
        run_id: string;
        component: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MixedGreenFunctionSliceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
